name: GreenMile
main: de.minestar.greenmile.core.GreenMileCore
version: ${pom.version}
depend: [MineStarLibrary]
commands:
  gm:
    description: Start/Stop a thread
    usage: /gm start world | /gm stop
  spawn:
    description: Teleport to the worldspawn
    usage: /spawn [worldname]