name: GreenMile
main: de.minestar.greenmile.Main
version: 1.3
commands:
  gm:
    description: Start/Stop a thread
    usage: /gm start world | /gm stop
  spawn:
    description: Teleport to the worldspawn
    usage: /spawn [worldname]